# Generated by Django 4.1.5 on 2023-03-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStudioApp', '0002_grade_instruments_programm_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
