# Generated by Django 4.1.5 on 2023-03-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStudioApp', '0003_songgenre_song_author_song_genre_song_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MusicStudioApp.songgenre'),
        ),
    ]
