# Generated by Django 4.1.5 on 2023-03-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStudioApp', '0004_alter_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='song',
            field=models.ManyToManyField(null=True, to='MusicStudioApp.song'),
        ),
    ]
