# Generated by Django 4.1.5 on 2023-03-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStudioApp', '0006_image_membergrade_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(null=True, to='MusicStudioApp.member'),
        ),
    ]
