# Generated by Django 4.1.5 on 2023-03-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStudioApp', '0009_alter_member_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='main_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_photo', to='MusicStudioApp.image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='photos', to='MusicStudioApp.image'),
        ),
    ]
