# Generated by Django 4.1.5 on 2023-03-19 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStudioApp', '0010_member_main_photo_alter_member_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='main_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_group_photo', to='MusicStudioApp.image'),
        ),
        migrations.AddField(
            model_name='group',
            name='photos',
            field=models.ManyToManyField(null=True, related_name='group_photos', to='MusicStudioApp.image'),
        ),
    ]
