# Generated by Django 4.1.5 on 2023-03-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStudioApp', '0012_alter_member_main_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('video', models.CharField(max_length=150)),
                ('photos', models.ManyToManyField(blank=True, related_name='concerts_photos', to='MusicStudioApp.image')),
            ],
        ),
    ]
