# Generated by Django 4.1.5 on 2023-03-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStudioApp', '0013_concerts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concerts',
        ),
    ]
