# Generated by Django 4.1.5 on 2023-03-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStudioApp', '0017_rename_concertss_concerts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concerts',
            new_name='Concert',
        ),
    ]
