# Generated by Django 4.1.5 on 2023-04-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicStudioApp', '0018_rename_concerts_concert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150, null=True)),
                ('middle_name', models.CharField(max_length=150, null=True)),
                ('phone_number', models.CharField(max_length=150)),
                ('instruments', models.ManyToManyField(null=True, to='MusicStudioApp.instruments')),
                ('main_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_teacher_photo', to='MusicStudioApp.image')),
            ],
        ),
    ]
